version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dietha-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    command:
      - --skip-character-set-client-handshake
    volumes:
      - dietha-mysql-data:/var/lib/mysql
    networks:
      - dietha-net

  app:
    image: jjuhhyu/dietha-app:latest
    container_name: dietha-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - dietha-net

volumes:
  dietha-mysql-data:

networks:
  dietha-net:
    driver: bridge